use storegames;

INSERT INTO TB_ADMIN (DS_NOME)
	values ('Luan');
INSERT INTO TB_ADMIN_LOGIN (FK_ADMIN, DS_LOGIN, DS_SENHA)
	values (1,'Luan', '1234');

-- CADASTRANDO USUARIO 
insert into TB_USUARIO (nm_usuario, ds_cep, ds_nascimento, ds_cpf)
	value('Kevin' , '04849-013' , '2000-02-12' , '0805393873537');

-- LOGIN USUARIO
INSERT INTO TB_USUARIO_LOGIN (id_usuario , ds_email, ds_senha)
	value(1, 'gabriel@gmail.com', '1234');




-- CARGA INICIAL, AQUI TA INSERINDO OS GENEROS E PLATAFORMAS DOS JOGOS
-- TEM QUE INSERIR PELO MENOS CAMPO EM CADA UMA DAS TABELAS

insert into TB_GENERO (DS_GENERO)
				VALUES('Aventura');
                
insert into TB_GENERO (DS_GENERO)
				VALUES('Ação');
                
insert into TB_GENERO (DS_GENERO)
				VALUES('Casual');


insert into tb_plataforma (ds_plataforma)
					values('Ps4');
                    
insert into tb_plataforma (ds_plataforma)
					values('Xbox');	


insert into TB_JOGO (NM_JOGO, VL_JOGO, DS_JOGO, QTD_ESTOQUE, IMG_CAPA, DS_REQUISITOS, BL_DISPONIVEL, BL_MAISVENDIDO)
					values('MINECRAFT', 80.00, 'JOGO DE ACAO', 17, '',  'INTEL I5', TRUE, TRUE );
		

insert into TB_JOGO (NM_JOGO, VL_JOGO, DS_JOGO, QTD_ESTOQUE, IMG_CAPA,  DS_REQUISITOS, BL_DISPONIVEL, BL_MAISVENDIDO)
					values('GTA 5', 50.00, 'JOGO DE AVENTURA', 15, '',  'INTEL I5', TRUE, TRUE );



-- INSERIR GENERO NO JOGO
INSERT INTO TB_GENERO_JOGO (FK_JOGO, FK_GENERO)
					 VALUES(1, 1);

-- INSERIR PLATAFORMA NO JOGO
INSERT INTO TB_PLATAFORMA_JOGO (FK_JOGO, FK_PLATAFORMA)
					     VALUES(1, 1);




-- VISUALIZA O JOGO COM O GENERO 
SELECT * 
FROM TB_JOGO AS J
INNER JOIN TB_GENERO_JOGO AS GJ 
ON GJ.FK_JOGO = J.ID_JOGO
INNER JOIN TB_GENERO AS G
ON G.ID_GENERO = GJ.FK_GENERO;

-- VISUALIZA O JOGO COM A PLATAFORMA 
SELECT *
FROM TB_JOGO AS J
INNER JOIN TB_PLATAFORMA_JOGO AS PJ 
ON PJ.FK_JOGO = J.ID_JOGO
INNER JOIN TB_PLATAFORMA AS P
ON P.ID_PLATAFORMA = PJ.FK_PLATAFORMA;

-- SELECT MALUCO
SELECT 
	JOG.ID_JOGO, JOG.NM_JOGO, CAT.DS_GENERO, PLAT.DS_PLATAFORMA
FROM TB_JOGO AS JOG
LEFT JOIN TB_GENERO_JOGO AS GJ ON GJ.FK_JOGO = JOG.ID_JOGO
LEFT JOIN TB_PLATAFORMA_JOGO AS PJG ON PJG.FK_JOGO = JOG.ID_JOGO
LEFT JOIN TB_GENERO AS CAT ON CAT.ID_GENERO = GJ.FK_GENERO
LEFT JOIN TB_PLATAFORMA AS PLAT ON PLAT.ID_PLATAFORMA = PJG.FK_PLATAFORMA
ORDER BY JOG.ID_JOGO;

-- SELECT PARA VER O PEDIDO COM O JOGO FORMA DE PAGAMENTO(SÓ PIX) E ENDEREÇO
SELECT J.NM_JOGO as nome, J.VL_JOGO, P.ID_PEDIDO as pedido, E.DS_ENDERECO AS endereco, PIX.NM_CLIENTE AS CLIENTE, PIX.DS_CPF AS CPF
FROM TB_JOGO J
LEFT JOIN TB_PEDIDO P
ON J.ID_JOGO = P.ID_PEDIDO
LEFT JOIN TB_ENDERECO E 
ON E.ID_ENDERECO = P.ID_PEDIDO
LEFT JOIN TB_PAGAMENTO_PIX PIX
ON PIX.ID_PAGAMENTO_PIX = P.ID_PEDIDO;


-- GET FILTRO DE PREÇO
-- SELECT 
-- 		   TB_JOGO.id_jogo,
-- 		   TB_JOGO.nm_jogo,
-- 		   TB_JOGO.vl_jogo,
-- 		   TB_JOGO.ds_jogo,
--            TB_JOGO.qtd_estoque,
--           TB_JOGO.bl_disponivel,
--            TB_JOGO.bl_maisvendido,
--            COUNT(TB_GENERO_JOGO.FK_GENERO),
--            COUNT(TB_PLATAFORMA_JOGO.FK_PLATAFORMA)
-- 	FROM TB_JOGO
-- 	INNER JOIN TB_GENERO_JOGO ON TB_JOGO.ID_JOGO = TB_GENERO_JOGO.FK_JOGO
-- 	INNER JOIN TB_PLATAFORMA_JOGO ON TB_JOGO.ID_JOGO = TB_PLATAFORMA_JOGO.FK_JOGO
--     WHERE VL_JOGO < 50
--     GROUP BY TB_JOGO.ID_JOGO,
-- 		     TB_JOGO.nm_jogo,
-- 		     TB_JOGO.vl_jogo,
-- 		     TB_JOGO.ds_jogo,
--              TB_JOGO.qtd_estoque,
-- 		     TB_JOGO.bl_disponivel,
--              TB_JOGO.bl_maisvendido;

-- GET FILTRO de preço
	SELECT 	
		   TB_JOGO.id_jogo,
		   TB_JOGO.nm_jogo,
		   TB_JOGO.vl_jogo
	FROM TB_JOGO
	where vl_jogo < 50;
	

-- GET FILTRO PARA PLATAFORMA